# Generated by Django 6.0.1 on 2026-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type_of_exposure', models.CharField(max_length=400)),
                ('type_of_material', models.CharField(max_length=400)),
                ('ward', models.CharField(max_length=400)),
                ('event_description', models.TextField()),
                ('actions_after_exposure', models.TextField()),
                ('medical_report', models.TextField()),
                ('patient_name', models.CharField(max_length=200)),
                ('personel_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
